update project 04-Lab-notes
lupomontero/bootcamp pull request #16
Opened 2020-09-24 16:08 UTC by reloadercf

add the frameworks section based on burger-queen and more. 👍 

 @AdrianaHY @merunga @lupomontero @betsyvies they could check it as soon as possible 👍

2020-09-24 16:51 UTC, reloadercf commented
@raulingg

2020-09-24 17:08 UTC, reloadercf reviewed
@raulingg

2020-09-24 17:18 UTC, raulingg commented on projects/04-lab-notes/README.md
> +Hoy en día no es práctico imaginar el desarrollo web sin HTML, CSS y JavaScript, esta última es el alma del desarrollo Frontend de aplicaciones web.
```suggestion
Hoy en día no es práctico imaginar el desarrollo web sin HTML, CSS y JavaScript, esta última es el alma del desarrollo de aplicaciones web.
```

2020-09-24 17:19 UTC, raulingg commented on projects/04-lab-notes/README.md
> +son algunos de los _Frameworks_ y _Librerías_ de JavaScript más utilizados por
```suggestion
son algunos de los _frameworks_ y _librerías_ de JavaScript más utilizados por
```

2020-09-24 17:19 UTC, raulingg commented on projects/04-lab-notes/README.md
> +Al elegir un _Framework_ o _Librería_ para nuestra interfaz, nos apoyamos en una
```suggestion
Al elegir un _framework_ o _librería_ para nuestra interfaz, nos apoyamos en una
```

2020-09-24 17:26 UTC, raulingg commented on projects/04-lab-notes/README.md
> +tener una herramienta en una web app para tomar notas, que nos permita crear, editar,
```suggestion
tener una herramienta como una web app para tomar notas, que nos permita crear, editar,
```

2020-09-24 17:28 UTC, raulingg commented on projects/04-lab-notes/README.md
> +de Laboratoria para desarrollar la idea, por lo cual te invitamos a colaborar.
```suggestion
de Laboratoria para implementar la idea, por lo cual te invitamos a colaborar.
```

2020-09-24 17:30 UTC, raulingg commented on projects/04-lab-notes/README.md
> +Para este proyecto necesitas crear una Web App con  `algún Framework de JavaScript` y `Firebase`.
```suggestion
Para este proyecto necesitas crear una Web App con  `cualquier librería o framework de JavaScript` y `Firebase`.
```

2020-09-24 17:31 UTC, raulingg commented on projects/04-lab-notes/README.md
> +* Cada usuarix deberá ver sus propias notas.
```suggestion
* Ver mis notas.
```

2020-09-24 17:33 UTC, raulingg commented on projects/04-lab-notes/README.md
> +pantalla. Para ello necesitaremos investigar acerca de `Router o Los módulos del sistema de rutas (en el Framework que tu elijas) ` y el
```suggestion
pantalla. Para ello necesitaremos investigar acerca de `la API para el manejo de rutas (en la librería o framework que elijas) ` y el
```

2020-09-24 17:36 UTC, raulingg commented on projects/04-lab-notes/README.md
> +concepto de `Single Page Application` además deberás seguir las recomendaciones para `PWAs (Progressive Web Apps)`.
No estoy seguro si `PWAs (Progressive Web Apps)` esta dentro de los requrimientos base de este proyecto :thinking:

2020-09-24 17:37 UTC, raulingg commented on projects/04-lab-notes/README.md
> +* `.gitignore`  este archivo contiene reglas para ignorar `/node_modules` u otras
```suggestion
* `.gitignore`  este archivo contiene reglas para ignorar `node_modules` u otras
```

2020-09-24 17:39 UTC, raulingg commented on projects/04-lab-notes/README.md
> +* `.eslintrc` este archivo contiene reglas para formatear el código además de ser una buena practica tener configurado un Linting.
```suggestion
* `.eslintrc` este archivo contiene reglas para formatear el código además de ser una buena practica tener configurado un linter.
```

2020-09-24 17:39 UTC, raulingg commented on projects/04-lab-notes/README.md
> +   el _Framework_ elegido. Todos estos Frameworks de
```suggestion
   el _framework_ elegido. Todos estos frameworks de
```

2020-09-24 17:43 UTC, raulingg commented on projects/04-lab-notes/README.md
> +interfaz debe actualizar la lista de notas).
```suggestion
   El objetivo principal de es aprender a construir una _interfaz web_ usando
   el _framework_ elegido. Todos estos frameworks de
   Frontend atacan el mismo problema: **cómo mantener la interfaz y el estado
   sincronizados**. Así que esta experiencia espera familiarizarte con el concepto
   de _estado de pantalla_, y cómo cada cambio sobre el estado se va a
   ir reflejando en la interfaz (por ejemplo, cada vez que agregamos una _nota_, la
interfaz debe actualizar la lista de notas).
```

2020-09-24 17:45 UTC, raulingg commented on projects/04-lab-notes/README.md
> +- [ ] Sass
```suggestion
- [ ] Sass
```
Que tal si prefieren usar puro css, o usar css-in-js. Es realmente Sass un objetivo aprendizaje para este proyecto ? :thinking:

2020-09-24 17:46 UTC, raulingg commented on projects/04-lab-notes/README.md
> +- [ ] Manejo del estado
```suggestion
- [ ] Manejo de estado
```

2020-09-24 17:49 UTC, raulingg commented on projects/04-lab-notes/README.md
> +* [ ] [`onAuthStateChanged`](https://firebase.google.com/docs/auth/web/manage-users?hl=es)
Pienso que es mejor mantener los recursos como links a documentacion oficial en su propio apartado.

2020-09-24 17:52 UTC, raulingg commented on projects/04-lab-notes/README.md
> +- Necesitamos pensar bien en el aspecto UX (podría adaptarse al contexto remoto) de quienes van a tomar las notas, el
> (podría adaptarse al contexto remoto) 

No pude entenderlo :confused:

2020-09-24 17:56 UTC, raulingg commented on projects/04-lab-notes/README.md
> +- [Angular vs React vs Vue](https://medium.com/somoswigou/angular-vs-react-vs-vue-cual-es-la-mejor-opción-941a207951c7)
Creo que este recurso no es necesario. Ultimadamente cada estudiante puede hacer su propia busqueda.

2020-09-24 17:57 UTC, raulingg commented on projects/04-lab-notes/README.md
>  ### Otros recursos
Aca podriamos colocar los recursos de las otras librerias y frameworks

2020-09-24 17:58 UTC, raulingg commented on projects/04-lab-notes/README.md
> +### Cloud functions
Es realmente necesario este recurso? tal vez me esto perdiendo de algo

2020-09-24 18:00 UTC, reloadercf commented on projects/04-lab-notes/README.md
> +concepto de `Single Page Application` además deberás seguir las recomendaciones para `PWAs (Progressive Web Apps)`.
me hice la misma pregunta pero lo deje para saber que opiniones había

2020-09-24 18:01 UTC, raulingg commented on projects/04-lab-notes/README.md
> +#### [Historia de usuario 1] Usuaria/o debe poder tomar nota
Nos faltarian escribir las otras HUs

2020-09-24 18:02 UTC, reloadercf commented on projects/04-lab-notes/README.md
> +interfaz debe actualizar la lista de notas).
quite esta info porque se repite en la parte superior (intro)

2020-09-24 18:02 UTC, reloadercf commented on projects/04-lab-notes/README.md
> +- [ ] Sass
es cierto no lo había pensado

2020-09-24 18:04 UTC, raulingg requested changes
@reloadercf deje varios comentarios que pueden ser de ayuda.

Gracias por ayudar a refinar este proyecto. :+1:

2020-11-09 17:52 UTC, lupomontero reviewed
Gracias por el PR @reloadercf :muscle: ... y disculpa por la demora en revisarlo... se me pasó la notificación y recién lo vi hoy.

He dejado un montón de comentarios y sugerencias, así que continuemos la conversación...

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +## Hacker Edition
```suggestion
## 6. Hacker Edition
```

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +* [Hacker Edition](#hacker-edition)
```suggestion
* [6. Hacker Edition](#6-hacker-edition)
```

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +### Cloud functions
Teniendo en cuenta la conversación en https://github.com/Laboratoria/bootcamp/issues/1006 me atrevería a quitar las cloud functions de este proyecto.

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +Hoy en día no es práctico imaginar el desarrollo web sin HTML, CSS y JavaScript, esta última es el alma del desarrollo de aplicaciones web.
Esta frase parece un copy/paste del primer párrafo del [post](https://medium.com/somoswigou/angular-vs-react-vs-vue-cu%C3%A1l-es-la-mejor-opci%C3%B3n-941a207951c7) que se sugiere más adelante en la sección de _otros recursos_. Si es una cita textual por favor pongámoslo como tal, como `blockquote` con mención y link a la cita. Por otro lado, no siento que agregue mucho valor al preámbulo como tal. ¿Qué opinan? :thinking:

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +Como desarrolladora Frontend, estos kits de desarrollo pueden resultarte
En los últimos años, como convención, hemos tratado de usar _front-end_ como _adjetivo compuesto_. Por ejemplo: una _front-end developer_, una chamba _front-end_, un curso de _front-end_, etc...

Por otro lado, para referirnos a una interfaz en sí como sustantivo, en ese caso la forma recomendada es _front end_ como dos palabras. Por ejemplo: El _front end_ lo diseñó Pepita, esa funcionalidad hay que implementarla en el _front end_, ...

Como referencia ver: https://css-tricks.com/poll-results-front-end-front-end/#the-right-answer-seems-to-be

```suggestion
Como desarrolladora front-end, estos kits de desarrollo pueden resultarte
```

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +tener una herramienta en una web app para tomar notas, que nos permita crear, editar,
Prefiero la versión anterior. En este momento no veo el valor agregado de estos cambios menores.

```suggestion
implementar una web app para tomar notas, que nos permita crear, editar,
```

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +Para este proyecto necesitas crear una Web App con  `algún Framework de JavaScript` y `Firebase`.
Preferiría ser todavía más agnóstico de tecnología de implementación. Este proyecto se podría hacer perfectamente Vanilla, con Electron, React Native, etc, etc, ... ¿qué les parece?

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +concepto de `Single Page Application` además deberás seguir las recomendaciones para `PWAs (Progressive Web Apps)`.
Me atrevería a decir que no... :thinking: 

```suggestion
concepto de `Single Page Application`.
```

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> -* `.editorconfig` este archivo contiene la configuración para editores de texto.
Por qué se ha quitado el archivo `.editorconfig`? Alguna motivación en particular?

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +- [ ] Sass
Yo dejaría a Sass fuera de los objetivos de este proyecto. No me parecería mal que alguien lo usara, al igual que otros, pre o post procesadores, o css-in-js, ...

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +- [ ] Sass
```suggestion
```

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +* [ ] [`onAuthStateChanged`](https://firebase.google.com/docs/auth/web/manage-users?hl=es)
@raulingg: Te animas con un PR?

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +- Necesitamos pensar bien en el aspecto UX (podría adaptarse al contexto remoto) de quienes van a tomar las notas, el
Tampoco entiendo el paréntesis agregado. A qué te refieres @reloadercf?

Por ahora propongo quitarlo.

```suggestion
- Necesitamos pensar bien en el aspecto UX de quienes van a tomar las notas, el
```

2020-11-09 17:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +- [Angular vs React vs Vue](https://medium.com/somoswigou/angular-vs-react-vs-vue-cual-es-la-mejor-opción-941a207951c7)
He _leído el post por encima_ y la verdad no me parece un recurso tan apropiado... las comparaciones propuestas con de popularidad, performace, etc, ... pero no creo que respondan a las preguntas que nuestras estudiantes normalmente tienen al tener que elegir un framework. Propongo quitarlo.

```suggestion
```

2020-11-11 22:08 UTC, merged