Add current version Lab-notes
lupomontero/bootcamp pull request #22
Opened 2021-11-05 02:00 UTC by reloadercf

Hola @lupomontero @mfdebian
en este PR se agrega la ultima versión de Lab-notes
donde a grandes rasgos se modifican un par de cosas y lo más importante,
se proponen 4 HU

ACK by @raulingg

2021-11-09 16:19 UTC, lupomontero commented
cc/ @mfdebian

2021-11-09 16:52 UTC, lupomontero requested changes
Gracias por el PR @reloadercf :muscle: 

He dejado varios comentarios y algunas sugerencias de cambios menores. El punto principal que todavía creo que nos toca resolver es la sección de _objetivos de aprendizaje_, que desde hace un tiempo quedó estandarizada en conjunto con un archivo `project.yml` (ver comentarios para más detalles).

2021-11-09 16:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +framework de JavaScript` y `Firebase`.
```suggestion
Para este proyecto necesitas crear una Web App con **cualquier librería o
framework de JavaScript** y **Firebase**.
```

Prefiero que reservemos las etiquetas `<code>` para snippets de código, y en esto casos usar énfasis (`_` => `<em>`) o _negrita/bold_ (`**` => `<strong>`).

2021-11-09 16:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +ser una buena practica tener configurado un linter.
```suggestion
  ser una buena practica tener configurado un linter.
```

whitespace :see_no_evil:

2021-11-09 16:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +## 3. Objetivos de Aprendizaje
La sección de _objetivos de aprendizaje_ se estandarizó en [`v3.0.0`](https://github.com/Laboratoria/bootcamp/releases/tag/v3.0.0) hace ya unos meses. Acá nos tocaría reemplazar este texto con el texto éstándar (es el mismo en todos los proyectos, [por ejemplo](https://github.com/Laboratoria/bootcamp/tree/main/projects/03-social-network#3-objetivos-de-aprendizaje)) y agregar los objetivos de aprendizaje específicos del proyecto en un archivo `project.yml` ([ver ejemplo](https://github.com/Laboratoria/bootcamp/blob/main/projects/03-social-network/project.yml)) en la raíz del proyecto (junto al `README.md`).

2021-11-09 16:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
>  de notas).
Este texto toca corregirlo (hay un typo en la primer línea - _El objetivo principal **de es** aprender..._) y además hay que moverlo a la sección de _resumen del proyecto_ para que se incluya en el readme que ven las estudiantes. Desde hace ya un tiempo el script [`create-cohort-project`](https://github.com/Laboratoria/bootcamp/tree/main/scripts#create-cohort-project) se encarga de reemplazar y generar esta sección a partir del archivo `project.yml`.

2021-11-09 16:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +semana cada uno.
```suggestion
* La duración estimada del proyecto es de 4 sprints, con una duración de una
  semana cada uno.
```

2021-11-09 16:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +#### [Historia de usuario 1] Usuaria/o debería poder tomar nota
```suggestion
#### [Historia de usuario 1] Usuaria debería poder tomar nota
```

:female_sign:

2021-11-09 16:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +#### [Historia de usuario 2] Usuaria/o debería poder ver las notas
```suggestion
#### [Historia de usuario 2] Usuaria debería poder ver las notas
```

2021-11-09 16:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +#### [Historia de usuario 3] Usuaria/o debería poder editar las notas
```suggestion
#### [Historia de usuario 3] Usuaria debería poder editar las notas
```

2021-11-09 16:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +#### [Historia de usuario 4] Usuaria/o debería poder borrar notas
```suggestion
#### [Historia de usuario 4] Usuaria debería poder borrar notas
```

2021-11-09 16:52 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +estaba.
```suggestion
  navegador se cierra, cuando la vuelva a abrir, la nota debería mostrarse como
  estaba.
```

2021-11-09 19:03 UTC, mfdebian reviewed
Muchas gracias por el pull request @reloadercf !!
Agregué solamente un par de cambios de sugerencia sobre la semántica de las historias de usuarias.

2021-11-09 19:03 UTC, mfdebian commented on projects/04-lab-notes/README.md
> +#### [Historia de usuario 1] Usuaria/o debería poder tomar nota
```suggestion
#### [Historia de usuaria 1] Debería poder tomar nota
```

2021-11-09 19:03 UTC, mfdebian commented on projects/04-lab-notes/README.md
> +#### [Historia de usuario 2] Usuaria/o debería poder ver las notas
```suggestion
#### [Historia de usuaria 2] Debería poder ver las notas
```

2021-11-09 19:03 UTC, mfdebian commented on projects/04-lab-notes/README.md
> +#### [Historia de usuario 3] Usuaria/o debería poder editar las notas
```suggestion
#### [Historia de usuaria 3] Debería poder editar las notas
```

2021-11-09 19:03 UTC, mfdebian commented on projects/04-lab-notes/README.md
> +#### [Historia de usuario 4] Usuaria/o debería poder borrar notas
```suggestion
#### [Historia de usuaria 4] Debería poder borrar notas
```

2021-11-09 20:02 UTC, lupomontero commented on projects/04-lab-notes/README.md
> +#### [Historia de usuario 1] Usuaria/o debería poder tomar nota
La opción propuesta por @mfdebian me parece más concisa :+1:

2021-11-18 16:49 UTC, reloadercf commented on projects/04-lab-notes/README.md
> +framework de JavaScript` y `Firebase`.
De acuerdo

2021-11-22 17:08 UTC, lupomontero approved these changes
Gracias @reloadercf por los cambios y agregar las sugerencias. LGTM :star:

2021-11-22 17:10 UTC, merged